syntax = "proto3";
package ws;

service EventsService{
  rpc messageCreate (GuildMessage) returns (NoResponse);
  rpc messageUpdate (GuildMessage) returns (NoResponse);
  rpc messageDelete (GuildMessage) returns (NoResponse);
  rpc messageReactionAdd (GuildMessageReaction) returns (NoResponse);
  rpc messageReactionRemove (GuildMessageReaction) returns (NoResponse);
  rpc guildMemberAdd (GuildMember) returns (NoResponse);
  rpc guildMemberUpdate (GuildMember) returns (NoResponse);
  rpc guildMemberRemove (GuildMember) returns (NoResponse);
  rpc channelCreate (GuildChannel) returns (NoResponse);
  rpc channelUpdate (GuildChannel) returns (NoResponse);
  rpc channelDelete (GuildChannel) returns (NoResponse);
  rpc guildCreate (Guild) returns (NoResponse);
  rpc guildUpdate (Guild) returns (NoResponse);
  rpc guildDelete (Guild) returns (NoResponse);
  rpc roleCreate (GuildRole) returns (NoResponse);
  rpc roleUpdate (GuildRole) returns (NoResponse);
  rpc roleDelete (GuildRoleDelete) returns (NoResponse);
  rpc voiceStateUpdate (GuildMemberVoiceState) returns (NoResponse);
}

/** Shared **/
message NoResponse { }

message Guild {
  string id = 1;
  string name = 2;
  string description = 3;
  string icon = 4;
  repeated string features = 5;
  string joinedAt = 6;
  int64 maxMembers = 7;
  string rulesChannelId = 8;
  string publicUpdatesChannelId = 9;
  string preferredLocale =  10;
  string ownerId =  11;
  int32 verificationLevel = 12;
  int32 premiumTier = 13;
  int32 mfaLevel = 14;
  string afkChannelId = 15;
  int32 afkTimeout = 16;
  string systemChannelId = 17;
  int32 systemChannelFlags = 18;
  int32 defaultMessageNotifications = 19;
  int32 explicitContentFilter = 20;
  bool premiumProgressBarEnabled = 21;
  int32 premiumSubscriptionCount = 22;
}

/** Message **/
message GuildMessage {
  string id = 1;
  string guildId = 2;
  string channelId = 3;
  GuildMember author = 4;
  string content = 5;
  MessageMention mentions = 6;
  repeated MessageAttachment attachments = 7;
  MessageReference reference = 8;
  string timestamp = 10;
  string edited_timestamp = 11;
}

message GuildMessageReaction{
  string messageId = 1;
  string messageAuthorId = 2;
  string channelId = 3;
  string guildId = 4;
  GuildMember author = 5;
  string authorId = 6;
  GuildEmoji emoji = 7;
}

message MessageReference {
  string messageId = 1;
  string guildId = 2;
  string channelId = 3;
  int32 type = 4;
}

message GuildEmoji{
  string id = 1;
  string name = 2;
  bool animated = 3;
}

message MessageAuthor {
  string id = 1;
  bool bot = 2;
  bool system = 3;
  string username = 4;
  string globalName = 5;
  string avatar = 6;
}

message MessageMention {
  bool everyone = 1;
  repeated MessageAuthor users = 2;
}

message MessageAttachment{
  string name = 1;
  string id = 2;
  int32 size = 3;
  string url = 4;
  string proxyURL = 5;
  int32 height = 6;
  int32 width = 7;
  string contentType = 8;
  string description = 9;
}

/** Member **/
message GuildMember {
  string id = 1;
  string username = 2;
  string guildId = 3;
  string globalName = 4;
  string displayName = 5;
  string nick = 6;
  string avatar = 7;
  string banner = 8;
  string userAvatar = 9;
  string userBanner = 10;
  bool bot = 11;
  bool system = 12;
  repeated string roleIds = 13;
  string joinedAt = 14;
  bool pending = 15;
  string discriminator = 16;
}

/** Channel **/
message GuildChannel {
  string id = 1;
  string guildId = 2;
  string name = 3;
  string topic = 4;
  int32 type = 5;
  string parentId = 6;
  int32 position = 7;
  string lastMessageId = 8;
  bool nsfw = 9;
  int32 rateLimitPerUser = 10;
  int32 userLimit = 11;
  int64 bitrate = 12;
  repeated ChannelPermissionOverwrites permissionOverwrites = 13;
}

message ChannelPermissionOverwrites {
  string id = 1;
  int32 type =2;
  string deny = 3;
  string allow = 4;
}

/** Role **/
message GuildRole {
  string id = 1;
  string name = 2;
  string guildId = 4;
  int32 color = 5;
  string permissions = 6;
  int32 position = 7;
  bool managed = 8;
  bool mentionable = 9;
  string flags = 10;
  string icon = 11;
  bool hoist = 12;
}

/** Role Delete **/
message GuildRoleDelete {
  string id = 1;
  string guildId = 2;
}

/** Voice State **/
message GuildMemberVoiceState {
  GuildMember member = 1;
  string guildId = 2;
  string channelId = 3;
  string sessionId = 4;
  bool deaf = 5;
  bool mute = 6;
  bool selfDeaf = 7;
  bool selfMute = 8;
  bool selfVideo = 9;
  bool suppress = 10;
}